#!/bin/bash
########################################
#                                      #
# From:    Robert Bruckmueller         #
# Email:   admin@mediadelivery.de      #
# Web:     mediadelivery.de            #
# Version: 1.2.1                       #
# Date:    05.01.15                    #
# License: GPL v3                      #
# http://www.gnu.org/copyleft/gpl.html #
#                                      #
########################################

################################
#                              #
# Config at backup-db.config   #
#                              #
################################
DIR=$(dirname "$(readlink -e "$0")")
source $DIR/backup-db.config

hash mutt 2>/dev/null || { echo >&2 "I require mutt but it's not installed.  Aborting."; exit 1; }
if [ $1 ]
then
   logdebug=true
else
   logdebug=false
fi

senemail() {
	betreff=$1
	body=$2
	attach=$3
	if [ -z $attach ]
	then
		if [ -z $emailuser ]
		then
			if mutt -e "set smtp_url=smtp://${emailsmtp}:${emailport}" -e "set ssl_starttls=$emailtls" -e "set from=$emailfrom" -s "$betreff" -- $emailto <<< "$body"
			then
				debugpost "Email wurde gesendet."
			else
				echo "Es gab ein Problem mit mutt. Bitte Prüfen Sie die Config."
				exit 1
			fi
		else
		    if [ mutt -e "set smtp_url=smtp://${emailuser}@${emailsmtp}:${emailport}" -e "set ssl_starttls=$emailtls" -e "set smtp_pass=$emailpass" -e "set from=$emailfrom" -s "$betreff" -- $emailto <<< "$body"
			then
				debugpost "Email wurde gesendet."
			else
				echo "Es gab ein Problem mit mutt. Bitte Prüfen Sie die Config."
				exit 1
			fi
		fi
	else
		if [ -z $emailuser ]
		then
        	if mutt -e "set smtp_url=smtp://${emailsmtp}:${emailport}" -e "set ssl_starttls=$emailtls" -e "set from=$emailfrom" -s "$betreff" -a /tmp/$filename.asc -- $emailto <<< "$body"
			then
				debugpost "Email wurde gesendet."
			else
				echo "Es gab ein Problem mit mutt. Bitte Prüfen Sie die Config."
				exit 1
			fi
		else
			if mutt -e "set smtp_url=smtp://${emailuser}@${emailsmtp}:${emailport}" -e "set ssl_starttls=$emailtls" -e "set smtp_pass=$emailpass" -e "set from=$emailfrom" -s "$betreff" -a /tmp/$filename.asc -- $emailto <<< "$body"
			then
				debugpost "Email wurde gesendet."
			else
				echo "Es gab ein Problem mit mutt. Bitte Prüfen Sie die Config."
				exit 1
			fi
		fi
	fi
}
debugpost(){
	text=$1
	if [ $logdebug = true ]
    then
    	echo $text
    fi
}

filename="db-`date +%d%m%Y%H%M`.sql"
if [ -z $dbpass ]
then
    dbdump="mysqldump -u $dbuser --all-databases --ignore-table=mysql.event"
else
    dbdump="mysqldump -u $dbuser --password=$dbpass --all-databases --ignore-table=mysql.event"
fi


if $dbdump  > /tmp/$filename
then
	debugpost "SQL Dump wurde erstellt."
else
	senemail "FEHLER: DB Backup" "Der SQL Dump konnte nicht erstellt werden."
	exit 1
fi

if gpg -a -r $gpgkey -o /tmp/$filename.asc --encrypt /tmp/$filename
then
	rm /tmp/$filename
	debugpost "SQL Dump wurde verschluesselt."
else
	rm /tmp/$filename
	senemail "FEHLER: DB Backup" "SQL Dump wurde Erstellt, konnte aber nicht verschluesselt werden."
    exit 1
fi
senemail "DB Backup $filename" "Das DB Backup $filename wurde erstellt." "yes"
rm /tmp/*.sql.asc
exit 0
